server/mysite/index/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('forgot/', views.forgot, name='forgot'),
    path('reset/', views.reset, name='reset'),
    path('mydata/', views.mydata, name='mydata'),
    path('logout/', views.logout, name='logout'),

    #AJAX functions
    path('update/<int:opt>', views.update, name='update'),
    path('devctl/<int:dev_id>', views.devctl, name='devctl'),
]

server/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('index.urls')),
]

server/mysite/templates/data.html
<!DOCTYPE html>
{% load static %}
{% load el_pagination_tags %}
<html lang="zh-CN">
<head>
    	<!-- Required meta tags -->
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    	<!--link rel="icon" type="image/x-icon" href="{% static 'index/favicon.ico' %}"-->
    	<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'index/data.css' %}">

    	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    	<script src="{% static 'jquery.min.js' %}"></script>
    	<script src="{% static 'bootstrap.min.js' %}"></script>

   	<!-- Optional JavaScript -->
   	<script src="{% static 'index/data.js' %}"></script>

    	<title>传感器数据(゜-゜)つロ</title>
</head>
  
<body class=my-sensor-page>
	<div class=container-fluid>
		<nav class="navbar navbar-light mynavbar" style="background-color: #e3f2fd;">			
			<a href="http://www.fafu.edu.cn/">
				<img src="{% static 'index/FAFUlogoblue.png' %}" class="img-responsive" alt=FAFU />
			</a>
			<ul class="nav masthead-nav">
				<li>当前在线：<a href="#">{{ request.session.user_account }}</a></li>
                  		<li>&emsp;&emsp;<a href="/logout/" style="color:blue">退出登录</a></li>
			</ul>
		</nav>
	</div>
			
	<div class=container-fluid>
		<div class="row">
			<div class="col-2 mysidebar">
				<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
					<a class="nav-link mynavcolor active" id="v-pills-present-data-tab" data-toggle="pill" href="#v-pills-present-data" role="tab" aria-controls="v-pills-present-data" aria-selected="true">当前数据</a>
					<a class="nav-link" id="v-pills-history-data-tab" data-toggle="collapse" href="#collapse-history-data" role="tab" aria-controls="v-pills-history-data" aria-selected="false">历史数据</a>
					<div class="collapse" id="collapse-history-data">
						<div class="nav flex-column nav-pills" id="v-collapse-pills-tab" role="tablist" aria-orientation="vertical">
							<a class="nav-link mynavcolor" id="v-pills-all-data-tab" data-toggle="pill" href="#v-pills-all-data" role="tab" aria-controls="v-pills-all-data" aria-selected="false">&emsp;全部数据</a>
							<a class="nav-link mynavcolor" id="v-pills-light-tab" data-toggle="pill" href="#v-pills-light" role="tab" aria-controls="v-pills-light" aria-selected="false">&emsp;光照强度</a>
							<a class="nav-link mynavcolor" id="v-pills-air-tempture-tab" data-toggle="pill" href="#v-pills-air-tempture" role="tab" aria-controls="v-pills-air-tempture" aria-selected="false">&emsp;空气温度</a>
							<a class="nav-link mynavcolor" id="v-pills-air-humidity-tab" data-toggle="pill" href="#v-pills-air-humidity" role="tab" aria-controls="v-pills-air-humidity" aria-selected="false">&emsp;相对空气湿度</a>
							<a class="nav-link mynavcolor" id="v-pills-soil-tempture-tab" data-toggle="pill" href="#v-pills-soil-tempture" role="tab" aria-controls="v-pills-soil-tempture" aria-selected="false">&emsp;土壤温度</a>
							<a class="nav-link mynavcolor" id="v-pills-soil-humidity-tab" data-toggle="pill" href="#v-pills-soil-humidity" role="tab" aria-controls="v-pills-soil-humidity" aria-selected="false">&emsp;相对土壤湿度</a>
						</div>
					</div>
					<a class="nav-link mynavcolor" id="v-pills-device-manage-tab" data-toggle="pill" href="#v-pills-device-manage" role="tab" aria-controls="v-pills-device-manage" aria-selected="false">设备管理</a>
					<a class="nav-link mynavcolor" id="v-pills-about-system-tab" data-toggle="pill" href="#v-pills-about-system" role="tab" aria-controls="v-pills-about-system" aria-selected="false">关于系统</a>
				</div>
			</div>
				
			<div class="col-10">
				<div class="tab-content" id="v-pills-tabContent">
					<div class="tab-pane fade show active" id="v-pills-present-data" role="tabpanel" aria-labelledby="v-pills-present-data-tab">
						<table class="table table-striped mytable">
							<thead>
								<tr>
								  <th scope="col">用户ID</th>
								  <th>传感器节点</th>
								  <th>光照强度(lx)</th>
								  <th>空气温度(℃)</th>
								  <th>相对空气湿度(%)</th>
								  <th>土壤温度(℃)</th>
								  <th>相对土壤湿度(%)</th>
								  
								</tr>
							</thead>
							<tbody>
								{% for item in node_list %}
								<tr id={{item.NODE}}>
									<td scope="col">{{item.UID_id}}</td>
									<td>{{item.NODE}}</td>
									<td>{{item.LIGHT}}</td>
									<td>{{item.AIRTEMP}}</td>
									<td>{{item.AIRHUMI}}</td>
									<td>{{item.SOILTEMP}}</td>
									<td>{{item.SOILHUMI}}</td>				  
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
					<div class="tab-pane fade" id="v-pills-all-data" role="tabpanel" aria-labelledby="v-pills-all-data-tab">
						<table class="table table-striped mytable">
							<thead>
								<tr>
								  <th scope="col">日期时间</th>
								  <th>用户ID</th>
								  <th>传感器节点</th>
								  <th>光照强度(lx)</th>
								  <th>空气温度(℃)</th>
								  <th>相对空气湿度(%)</th>
								  <th>土壤温度(℃)</th>
								  <th>相对土壤湿度(%)</th>
								  
								</tr>
							</thead>
							<tbody>
								{% paginate summary_objs %}
								{% for item in summary_objs %}
								<tr>
								  <th scope="row">{{item.CREATETIME}}</th>
								  <td>{{item.UID_id}}</td>
								  <td>{{item.NODE}}</td>
								  <td>{{item.LIGHT}}</td>
								  <td>{{item.AIRTEMP}}</td>
								  <td>{{item.AIRHUMI}}</td>
								  <td>{{item.SOILTEMP}}</td>
								  <td>{{item.SOILHUMI}}</td>				  
								</tr>
								{% endfor %}
								
							</tbody>
						</table>
						<div style="text-align: center;">{% show_pages %}</div>
					</div>
					<div class="tab-pane fade" id="v-pills-light" role="tabpanel" aria-labelledby="v-pills-light-tab">
						<table class="table table-striped mytable">
							<thead>
								<tr>
								  <th scope="col">日期时间</th>
								  <th>用户ID</th>
								  <th>传感器节点</th>
								  <th>光照强度(lx)</th>
								</tr>
							</thead>
							<tbody>
								{% paginate light_objs %}
								{% for item in light_objs %}
								<tr>
								  <th scope="row">{{item.CREATETIME}}</th>
								  <td>{{item.UID_id}}</td>
								  <td>{{item.NODE}}</td>
								  <td>{{item.LIGHT}}</td>		  
								</tr>
								{% endfor %}			
							</tbody>
						</table>
						<div style="text-align: center;">{% show_pages %}</div>
					</div>
					<div class="tab-pane fade" id="v-pills-air-tempture" role="tabpanel" aria-labelledby="v-pills-air-tempture-tab">
						<table class="table table-striped mytable">
							<thead>
								<tr>
								  <th scope="col">日期时间</th>
								  <th>用户ID</th>
								  <th>传感器节点</th>
								  <th>空气温度(℃)</th>
								</tr>
							</thead>
							<tbody>
								{% paginate airtemp_objs %}
								{% for item in airtemp_objs %}
								<tr>
								  <th scope="row">{{item.CREATETIME}}</th>
								  <td>{{item.UID_id}}</td>
								  <td>{{item.NODE}}</td>
								  <td>{{item.AIRTEMP}}</td>		  
								</tr>
								{% endfor %}	
							</tbody>
						</table>
						<div style="text-align: center;">{% show_pages %}</div>
					</div>
					<div class="tab-pane fade" id="v-pills-air-humidity" role="tabpanel" aria-labelledby="v-pills-air-humidity-tab">
						<table class="table table-striped mytable">
							<thead>
								<tr>
								  <th scope="col">日期时间</th>
								  <th>用户ID</th>
								  <th>传感器节点</th>
								  <th>相对空气湿度(%)</th>
								</tr>
							</thead>
							<tbody>
								{% paginate airhumi_objs %}
								{% for item in airhumi_objs %}
								<tr>
								  <th scope="row">{{item.CREATETIME}}</th>
								  <td>{{item.UID_id}}</td>
								  <td>{{item.NODE}}</td>
								  <td>{{item.AIRHUMI}}</td>		  
								</tr>
								{% endfor %}	
							</tbody>
						</table>
						<div style="text-align: center;">{% show_pages %}</div>
					</div>
					<div class="tab-pane fade" id="v-pills-soil-tempture" role="tabpanel" aria-labelledby="v-pills-soil-tempture-tab">
						<table class="table table-striped mytable">
							<thead>
								<tr>
								  <th scope="col">日期时间</th>
								  <th>用户ID</th>
								  <th>传感器节点</th>
								  <th>土壤温度(℃)</th>
								</tr>
							</thead>
							<tbody>
								{% paginate soiltemp_objs %}
								{% for item in soiltemp_objs %}
								<tr>
								  <th scope="row">{{item.CREATETIME}}</th>
								  <td>{{item.UID_id}}</td>
								  <td>{{item.NODE}}</td>
								  <td>{{item.SOILTEMP}}</td>		  
								</tr>
								{% endfor %}			
							</tbody>
						</table>
						<div style="text-align: center;">{% show_pages %}</div>
					</div>
					<div class="tab-pane fade" id="v-pills-soil-humidity" role="tabpanel" aria-labelledby="v-pills-soil-humidity-tab">
						<table class="table table-striped mytable">
							<thead>
								<tr>
								  <th scope="col">日期时间</th>
								  <th>用户ID</th>
								  <th>传感器节点</th>
								  <th>相对土壤湿度(%)</th>
								</tr>
							</thead>
							<tbody>
								{% paginate soilhumi_objs %}
								{% for item in soilhumi_objs %}
								<tr>
								  <th scope="row">{{item.CREATETIME}}</th>
								  <td>{{item.UID_id}}</td>
								  <td>{{item.NODE}}</td>
								  <td>{{item.SOILHUMI}}</td>		  
								</tr>
								{% endfor %}		
							</tbody>
						</table>
						<div style="text-align: center;">{% show_pages %}</div>
					</div>
					<div class="tab-pane fade" id="v-pills-device-manage" role="tabpanel" aria-labelledby="v-pills-device-manage-tab">
						<table class="table table-striped mytable">
							<thead>
								<tr>
								  <th scope="col">水泵状态</th>
								  <th>灯状态</th>
								</tr>
							</thead>
							<tbody>
								<tr>
								  <th scope="row">						
									<div class="btn-group" id=pump-group>
									      <button class="btn btn-lg btn-default" id=pump_on>ON</button>
									      <button class="btn btn-lg btn-primary" id=pump_off>OFF</button>
									</div>
								  </th>
								  <th>
									<div class="btn-group" id=lamp-group>
									      <button class="btn btn-lg btn-default" id=lamp_on>ON</button>
									      <button class="btn btn-lg btn-warning" id=lamp_off>OFF</button>
									</div>
								  </th>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="tab-pane fade" id="v-pills-about-system" role="tabpanel" aria-labelledby="v-pills-about-system-tab">
							<br/>&emsp;&emsp;欢迎使用远程温室智能监控系统!(版本号：V1.0)
							<ul>
								<li>如果您想提交一些漏洞或者意见,邮箱联系510924866@qq.com,这对我们非常有帮助!</li>
								<li>如果您对该系统的开发感兴趣,也可以联系以上邮箱,我们十分欢迎您的加入。</li>
								<li>我们的联系地址：福建省福州市仓山区福建农林大学田家炳C栋304。</li>		
							</ul>
					</div>						
				</div>
			</div>			
		</div>
	</div>
	<div class=container-fluid>
		<div class="myfooter">
			Copyright &copy; 2018 &mdash; TianC304@FAFU 
		</div>
	</div>
	<!--h1>Ajax Test</h1>  
	<p id="time"></p>  
	<p id="content1"></p>
	<p id="content2"></p>
	<p id="content3"></p-->  
</body>
</html>

server/mysite/templates/forgot.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>忘记密码(╯°口°)╯(┴—┴</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'index/my-login.css' %}">
</head>
<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center align-items-center h-100">
				<div class="card-wrapper">
					{% if message %}
				      	<div class="alert alert-warning">{{ message }}</div>
				  	{% endif %}
					
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">忘记密码</h4>
							<form action="/forgot/" method="POST">
							  {% csrf_token %}
							        
								<div class="form-group">
									<label for="account">帐号：</label>
									<input id="account" type="text" class="form-control" name="account" placeholder="Account" value="" required autofocus>
								</div>

								<div class="form-group">
									<label for="email">邮箱地址：</label>
									<input id="email" type="email" class="form-control" name="email" placeholder="E-Mail Address" value="" required>
									<div class="form-text text-muted">
										点击“重置密码”我们将给您的邮箱发送重置密码的链接
									</div>
								</div>

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block">
										重置密码
									</button>
								</div>
								<div class="margin-top20 text-center">
									我记起来了!<a href="{% url 'index:login' %}">去登录</a>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; 2018 &mdash; TianC304@FAFU 
					</div>
				</div>
			</div>
		</div>
	</section>
</body>
</html>

server/mysite/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
    	<!-- Required meta tags -->
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<title>Welcome!!! (>ε<)</title>
</head>
<body>
	<p style="text-align:center;"><img src="{% static 'index/smile_half.jpeg' %}" class="img-responsive" alt=LOGO /></p>
	<h1 style="text-align:center;margin-top:20px;">
		欢迎使用远程温室智能监控系统!(版本号：V1.0)
		<br />如果您想提交一些漏洞或者意见,邮箱联系510924866@qq.com,这对我们非常有帮助!
		<br />如果您对该系统的开发感兴趣,也可以联系以上邮箱,我们十分欢迎您的加入。
	</h1>
	<h1 style="text-align:center;"><a href="{% url 'index:login' %}">点我跳转到登录页面</a></h1>
	<div style="margin: 60px 0;color: #888;text-align: center;">
		Copyright &copy; 2018 &mdash; TianC304@FAFU 
	</div>
</body>
</html>

server/mysite/templates/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>欢迎(゜-゜)つロ</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'index/my-login.css' %}">
</head>
<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
				  	{% if message %}
				      	<div class="alert alert-warning">{{ message }}</div>
				  	{% endif %}

					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">用户登录</h4>
							<form action="/login/" method="POST">
							  {% csrf_token %}
							 
								<div class="form-group">
									<label for="account">帐号：</label>

									<input id="account" type="text" class="form-control" name="account" placeholder="Account" value="" autofocus>
								</div>

								<div class="form-group">
									<label for="password">密码：
									</label>
									<input id="password" type="password" class="form-control" placeholder="Password" name="password">
								</div>
                                                             
								<div class="form-group">
									<label>
										<input type="checkbox" name="remember"> 记住我
										<a href="{% url 'index:forgot' %}" class="float-right">
											忘记密码?
										</a>
									</label>
								</div>

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block">
										登录
									</button>
								</div>
								<div class="margin-top20 text-center">
									没有帐号? <a href="{% url 'index:register' %}">注册</a>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; 2018 &mdash; TianC304@FAFU 
					</div>
				</div>
			</div>
		</div>
	</section>

	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'index/my-login.js' %}"></script>
</body>
</html>

server/mysite/templates/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>注册(￣3￣)</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'index/my-login.css' %}">
</head>
<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					{% if message %}
				      	<div class="alert alert-warning">{{ message }}</div>
				  	{% endif %}

					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">注册</h4>
							<form action="/register/" method="POST">
							  {% csrf_token %}

								<div class="form-group">
									<label for="account">帐号：</label>
									<input id="account" type="text" class="form-control" name="account" placeholder="Account" required autofocus>
								</div>

								<div class="form-group">
									<label for="password">密码：</label>
									<input id="password" type="password" class="form-control" name="password" placeholder="Password" required>
								</div>

								<div class="form-group">
									<label for="confirm">密码确认：</label>
									<input id="confirm" type="password" class="form-control" name="confirm" placeholder="Confirm Password" required>
								</div>

								<div class="form-group">
									<label for="email">邮箱地址：</label>
									<input id="email" type="email" class="form-control" name="email" placeholder="E-Mail Address" required>
								</div>

								<div class="form-group">
									<label for="code">邀请码：</label>
									<input id="code" type="text" class="form-control" name="code" placeholder="Invitation code" required>
								</div>
								<!--div class="form-group">
									<label>
										<input type="checkbox" name="aggree" value="1"> I agree to the Terms and Conditions
									</label>
								</div-->

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block">
										注册
									</button>
								</div>
								<div class="margin-top20 text-center">
									已经有一个帐号了? <a href="{% url 'index:login' %}">去登录</a>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; 2018 &mdash; TianC304@FAFU
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'jquery.min.js' %}"></script>
	<script src="{% static 'bootstrap.min.js' %}"></script>
	<script src="{% static 'index/my-login.js' %}"></script>
</body>
</html>

server/mysite/templates/reset.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>重置密码(〜￣△￣)〜</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'index/my-login.css' %}">
</head>
<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center align-items-center h-100">
				<div class="card-wrapper">
					{% if message %}
				      	<div class="alert alert-warning">{{ message }}</div>
				  	{% endif %}

					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">重置密码</h4>
							<form method="POST">
							  {% csrf_token %}

							  	<div class="form-group">
									<label for="rstcode">重置码:</label>
									<input id="rstcode" type="text" class="form-control" name="rstcode" placeholder="Reset code" required autofocus>
								</div>

								<div class="form-group">
									<label for="newpwd">新密码:</label>
									<input id="newpwd" type="password" class="form-control" name="newpwd" placeholder="New Password">
									<div class="form-text text-muted">
										请确保您的密码有足够的强度且容易记住
									</div>
								</div>

								<div class="form-group no-margin">
									<button type="submit" class="btn btn-primary btn-block">
										重置密码
									</button>
								</div>
							</form>
						</div>
					</div>
					<div class="footer">
						Copyright &copy; 2018 &mdash; TianC304@FAFU 
					</div>
				</div>
			</div>
		</div>
	</section>

	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'index/my-login.js' %}"></script>
</body>
</html>

server/mysite/templates/test.html
<html>  
 <head>  
   <title>Ajax Test</title>  
   <script src="http://cdn.bootcss.com/jquery/1.10.2/jquery.min.js"></script>  
   <script type="text/javascript" language="javascript">  
           function update(id) {  
               $.getJSON('/testdata/' + id + "/",function(a_para_name_present_jsondata) {  
                $.each(a_para_name_present_jsondata, function(){  
                    $("#content").html('<p>' + this.name + ' is a ' + this.subject + ' teacher.</p>');  
                });  
               });  
           }  
           function timeDown(limit, i) {  
               limit--;  
               if (i > 4) {  
                   i = 0;  
               }  
               if (limit < 0) {  
                   limit = 3;  
                   update(i);  
                   i++;  
               }  
               $('#time').text(limit + '秒后刷新');  
               setTimeout(function() {  
                   timeDown(limit, i);  
               }, 1000)  
           }  

           $(document).ready(function() {  
               timeDown(3, 0)
        })  
   </script>  
 </head>  
 <body>  
   <h1>Ajax Test</h1>  
   <p id="time"></p>  
   <div id="content"></div>   
 </body>  
</html>  

server/mysite/templates/tologin.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
    	<!-- Required meta tags -->
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<title>ERROR! T_T</title>
</head>
<body>
	<p style="text-align:center;"><img src="{% static 'index/emojixx.jpeg' %}" class="img-responsive" alt=ERROR /></p>
	<h1 style="text-align:center;margin-top:20px;">您还未登录，无法查看数据!</h1>
	<h1 style="text-align:center;"><a href="{% url 'index:login' %}">我要去登录</a></h1>
	<div style="margin: 60px 0;color: #888;text-align: center;">
		Copyright &copy; 2018 &mdash; TianC304@FAFU 
	</div>
</body>
</html>